### ISSUE TITLE
configuration.resolve has an unknown property 'fallback'

### ISSUE THREAD

**Issue by sbnajardhane** [LearnWebCode/handlebars-webpack#1]
Hi, 
`
    Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
     - configuration.resolve has an unknown property 'fallback'. These properties are valid: object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?,  extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }`

I am getting this error when I tried to build using webpack. I have installed node modules. 

`
// resolve: {
  //   fallback: path.join(__dirname, "./js/helpers")
  // },`

I have commented this in config file and build was successful and working fine.
I researched about the fallback config but find something useful, can you please help me out here. @LearnWebCode Brad Schiff 
Thanks
Shubham

**Comment by LearnWebCode** [comment]
Hi @sbnajardhane, webpack has changed the way their main API works since I created this webpack lesson. However, I just pushed a new commit that should fix things. If you want to try a fresh clone (so you can be sure to get my latest package.json and rebuild node_modules) you should be good to go now.

The only thing to be aware of is in my new setup - when you call helpers in a handlebars template, you no longer need to include the dollar symbol ($). You can check my example files to see what I mean.

**Comment by sbnajardhane** [comment]
Thanks a lot @LearnWebCode changes are working fine.
I am facing an issue with my design of the project. Below is my directory structure.
- plugins
    - plugin_1
    - plugin_2
    - plugin_3
- common_js
    - handlebar.js
Single plugin or two or all plugins may be triggered on webpage. So I have inserted handlebar.js as common for all and separate template handling for each plugin. Now I want to use bundler to bundle my js file, but handlebar-loader also injecting handlebar.js into final bundle. So it is getting repeated in each plugin. Do you have any idea how to exclude handlebar.js from each plugin while bundling?
